#
# file:			check_merge_to_master.yml  
# created on:	2023 Feb 03  
#
# usefull urls:
#				1. https://docs.github.com/en/actions
#				2. https://github.com/actions/starter-workflows
#				3. https://github.com/actions/download-artifact
#

name: check-merge-to-master-and-develop
on:
    pull_request:
        branches: [ master, develop ]

env:
  deployUser: kalantar
  #deployRoot: /home/${{env.deployUser}}/build/3rd-party
  #deployHost: mtcapitzcpu7.ifh.de
  #deployHostAndUser: ${{env.deployUser}}@${{env.deployHost}}


jobs:

    # matrix for unix systems (for now ubuntu-20.04 and ubuntu-22.04, and macos)
    unixes:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
        steps:
            - name: Checking out repository
              uses: actions/checkout@v3
    
            - name: Preparing host for ${{ matrix.os }}
              run: ./scripts/unix_prepare_host.sh
      
            - name: Preparing repository for ${{ matrix.os }}
              run: ./scripts/unix_prepare_repository.sh

            - name: Building for ${{ matrix.os }}
              run: ./scripts/unix_build_all.sh

            - name: testing test apps for for ${{ matrix.os }}
              run: ./scripts/unix_run_tests.sh


    # This is for windows
    windows:
        runs-on: windows-latest
        steps:
            - name: Checking out repository
              uses: actions/checkout@v3

            - name: Setup MSBuild.exe
              uses: microsoft/setup-msbuild@v1.1

            - name: Setup developer command prompt
              uses: ilammy/msvc-dev-cmd@v1

            - name: Developer host preparation
              run: cmd /C "call .\scripts\windows_prepare_host.bat"
              #working-directory: core

            - name: Repository preparation
              run: cmd /C "call .\scripts\windows_prepare_repository.bat"

            - name: Compiling cinternal all tests
              run: >
                cmd /C "call .\scripts\windows_build_all.bat"

            - name: testing test apps
              run: cmd /C "call .\scripts\windows_run_tests.bat"
